app/ControlApp/urls.py
from django.urls import path
from . import views

app_name = 'ControlApp'
urlpatterns = [ 
    path('', views.to_nodered_recipes,name='noderedrecipes'),
]

app/HomeApp/urls.py
from django.urls import path
# from django.contrib.auth.decorators import login_required

from . import views

app_name = 'HomeApp'
urlpatterns = [ 
    path('home', views.to_nodered_control,name='noderedcontrol'),
]

app/MonitorApp/urls.py
from django.urls import path
# from django.contrib.auth.decorators import login_required

from . import views

app_name = 'MonitorApp'
urlpatterns = [ 
    path('', views.to_grafana,name='grafana'),
]

app/RedesApp/urls.py
from django.urls import path

from . import views

app_name = 'RedesApp'
urlpatterns = [
    path('', views.to_redes,name='redes'),
    path('update_datos',views.update_datos,name='update_datos'),
    #path('update_table',views.update_table,name='update_table'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(template_name='login.html'), name='login'),
    path('salir', LogoutView.as_view(template_name="salir", next_page='/'), name="salir"),
    path('hamaca/', include('HomeApp.urls')),
    path('hamaca/monitor/', include('MonitorApp.urls')),
    path('hamaca/control/', include('ControlApp.urls')),
    path('hamaca/redes/', include('RedesApp.urls')), 
    path('hamaca/procesamiento/', include('ProcesamientoApp.urls')),
    path('hamaca/configuracion/', include('ConfiguracionApp.urls')),   
]

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <title>HAMACA</title>
    <meta name="description" content="Webapp de control de Smart Gateway">
    <meta name="author" content="Pedro Boll">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Estilos personales para el template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'css/dashboard.css' %}" rel="stylesheet"> -->

    <!-- Estilos para iconos de FontAwesome -->
<!--     <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet"> -->

    <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
    <script defer src="{% static 'js/fontawesome/fa-brands.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/fa-regular.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/fa-solid.js' %}"></script>
    <script src="{% static 'js/fontawesome/fontawesome-all.js' %}"></script>

</head>
<body>
  <div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar">
      <div class="sidebar-header">
        <h5>
          <strong>
            <center>
              <img src="{% static 'images/hamaca_logo1.png' %}" alt="HAMACA Logo"  width="28" height="28">
              <span class=""></span>
              HAMACA
            </center>
          </strong>
        </h5>
        <span class=""></span> 
      </div>
      <div class="sidebar">
        <center>
          <ul class="list-unstyled components">
            <li class="active">
              <a href="{% url 'HomeApp:noderedcontrol' %}">
                <i class="fas fa-home"></i>
                <p>Hogar</p>
              </a>
            </li>
            <li class="">
              <a href="{% url 'MonitorApp:grafana' %}">
                <i class="fas fa-chart-line"></i>
                <p>Monitoreo</p>
              </a>
            </li>
            <li class="">
              <a href="{% url 'ControlApp:noderedrecipes' %}">
                <i class="fas fa-toggle-on"></i>
                <p>Control</p>
              </a>
            </li>
            <li class="">
              <a href="{% url 'RedesApp:redes' %}">
              <i class="fas fa-signal"></i>
              <p>Redes</p>
            </a>
            </li>
            <!-- <li class="">
              <a href="{% url 'ProcesamientoApp:procesamiento' %}">
                <i class="fas fa-cogs"></i>
                <p>Procesamiento</p>
            </a>
            </li> -->
            <li class="">
              <a href="{% url 'ConfiguracionApp:configuracion' %}">
                  <i class="fas fa-wrench"></i>  
                  <p>Configuraci&oacute;n</p>
              </a>
            </li>
          </ul>
        </center>
      </div>
      <div id="botonlogout">
        <center> 
          <button type="button" id="logout" class="btn btn-secondary navbar-btn">
            <a href="{% url 'salir' %}" style="color:#333;text-decoration:none">
              <span id="logoutText">Cerrar Sesi&oacute;n</span>
              <i class="fas fa-sign-out-alt"></i>
            </a>
          </button>
        </center> 
      </div>
    </nav>
    <div id="content">
      <div class="container bordes-nulos">
        <!-- Contenido especifico no heredado de base -->
        {% block contenido %}
        
        {% endblock contenido %}
      </div>
    </div>
  </div>


  <!-- Bootstrap core JavaScript
  ================================================== 
  Colocados al final del documento para permitir carga mas veloz -->
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap/bootstrap.js' %}"></script>
  <script src="{% static 'js/dashboard.js' %}"></script>
    
</body>
</html>

app/templates/login.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Webapp de control de Smart Gateway">
    <meta name="author" content="Pedro Boll">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

    <title>HAMACA</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <script defer src="{% static 'js/fontawesome/fa-brands.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/fa-regular.js' %}"></script>
    <script defer src="{% static 'js/fontawesome/fa-solid.js' %}"></script>
    <script src="{% static 'js/fontawesome/fontawesome-all.js' %}"></script>

  </head>

  <body class="text-center" style="background-color:#41474d;">
    <main role="main" class="container">
      <form class="form-signin" method="post">
        {% csrf_token %}
        <img src="{% static 'images/hamaca_logo2.png' %}" alt="HAMACA Logo"  width="200" height="200">
        <br><br>
        <h2 class="h3 mb-3 font-weight-normal">Bienvenido</h2>
        <br>
        <h5>Por favor, Inicie Sesi&oacute;n</h5>
        <br>
        <label for="inputUser" class="sr-only">Usuario</label>
        <div class="input-group">
          <!-- <span class="input-group-addon" id="basic-addon1"><i class="fa fa-user" aria-hidden="true"></i></span> -->
          <input type="user" id="inputUser" class="form-control" placeholder="usuario" name="username"required autofocus>
        </div>
        <label for="inputPassword" class="sr-only">Contrase&ntilde;a</label>
        <div class="input-group">
          <!-- <span class="input-group-addon" id="basic-addon2"><i class="fa fa-key" aria-hidden="true"></i></span> -->
          <input type="password" id="inputPassword" class="form-control" placeholder="contrase&ntilde;a" required name="password">
        </div>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Iniciar Sesi&oacute;n</button>
        <br><br><br><br><br><br><br>
      </form>
      <footer class="footer">
        <div class="container">
          <p class="mt-6 mb-6 text-muted">2023 &copy;- Desarrollado por Pedro Luis Boll Lugo</p>
          <p class="mt-6 mb-6 text-muted">Creditos reservados.</p>
        </div>
      </footer>
    </main>

  </body>
</html>